follow_sets = {
    'S': {'$'},
    'MAIN': {'$'},
    'FLIST': {'$'},
    "FLIST'": {'$'},
    'FDEF': {'def', '$'},
    'PARLIST': {')'},
    "PARLIST'": {')'},
    'VARLIST': {';'},
    "VARLIST'": {';'},
    'STMT': {'}', 'def', 'int', 'id', 'print', 'return', 'if', ';', '$'},
    'ATRIBST': {';'},
    "ATRIBST'": {';'},
    'ATRIBST_ID_SUFFIX': {';'},
    'PARLISTCALL': {')'},
    "PARLISTCALL'": {')'},
    'PRINTST': {';'},
    'RETURNST': {';'},
    "RETURNST'": {';'},
    'IFSTMT': {'}', 'def', 'int', 'id', 'print', 'return', 'if', ';', '$'},
    "IFSTMT'": {'}', 'def', 'int', 'id', 'print', 'return', 'if', ';', '$'},
    'STMTLIST': {'}'},
    "STMTLIST'": {'}'},
    'EXPR': {')', ';'},
    "EXPR'": {')', ';'},
    'NUMEXPR': {'<', '<=', '>', '>=', '==', '!=', ')', ';'},
    "NUMEXPR'": {'<', '<=', '>', '>=', '==', '!=', ')', ';'},
    'TERM': {'+', '-', '<', '<=', '>', '>=', '==', '!=', ')', ';'},
    "TERM'": {'+', '-', '<', '<=', '>', '>=', '==', '!=', ')', ';'},
    'FACTOR': {'*', '/', '+', '-', '<', '<=', '>', '>=', '==', '!=', ')', ';'}
}